name: Test App 
on: 
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Test App
        uses: STEM-C/auto/mocks@v0.7.1
        #with:
          #github_token: "${{ secrets.GITHUB_TOKEN }}"
